version: '3.8'

services:
  cloudflared:
    build: .
    container_name: cloudflared
    volumes:
      - ./cert/wsl@pc.pem:/etc/cloudflared/cert.pem
      - ./start-cloudflared.sh:/usr/local/bin/start-cloudflared.sh
    ports:
      - 22:22 # Map host's 22 port to container's 22 port
      - 2222:2222 # Map host's 2222 port to container's 2222 port
      - 3310:3310
    restart: always

  # mysql-master:
  #   image: registry.cn-shanghai.aliyuncs.com/alice52/dev-mysql-master-5.7:20201221.1161b86
  #   restart: 'on-failure:3'
  #   container_name: dev-mysql-master
  #   command: --skip-innodb-adaptive-hash-index
  #     --character-set-server=utf8mb4
  #     --collation-server=utf8mb4_general_ci
  #     --explicit_defaults_for_timestamp=true
  #     --lower_case_table_names=1
  #     --max_allowed_packet=128M
  #     --sql-mode="STRICT_TRANS_TABLES,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION,NO_ZERO_DATE,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: -pl,mko0
  #     TZ: Asia/Shanghai
  # ports:
  #   - 3306:3306
