name: Sync Github to Gitee

on:
  push:
  schedule:
    - cron:  '25 18 * * *'

jobs:
  main:
    runs-on: ubuntu-20.04
    steps:
    - name: Sync Github to Gitee
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/Alice52
        dst: gitee/alice52_xz
        dst_key: ${{ secrets.GITEE_SSH_KEY }}
        dst_token: ${{ secrets.GITEE_API_TOKEN }}
        black_list: ".github,C,dotfiles"
        account_type: user
        force_update: true
        debug: true
