name: Sync Github Orgs to Gitee

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Mannual Trigger Tags'
        required: false
        type: boolean
  push:
  schedule:
    - cron: '16 18 * * *'

jobs:
  main:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - name: Get wpp private repository list
        id: wpp_repo
        uses: yi-Xu-0100/repo-list-generator@v1.1.1
        with:
          user: wordpress-plus
          my_token: ${{ secrets.WPP_HUB_API_TOKEN }}
      - name: Sync Org(wordpress-plus) to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/wordpress-plus
          dst: gitee/wordpress-plus
          dst_key: ${{ secrets.GITEE_SSH_KEY }}
          dst_token: ${{ secrets.GITEE_API_TOKEN }}
          black_list: '.github,.github-private'
          static_list: ${{ steps.wpp_repo.outputs. repoList_ALL }}
          src_account_type: org
          dst_account_type: org
          clone_style: ssh
          force_update: true
          debug: true

      - name: Get wordpress-plus-ultra private repository list
        id: wppu_repo
        uses: yi-Xu-0100/repo-list-generator@v1.1.1
        with:
          user: wordpress-plus-ultra
          my_token: ${{ secrets.FULL_KEY }}
      - name: Sync Org(wordpress-plus-ultra) to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/wordpress-plus-ultra
          dst: gitee/wordpress-plus
          dst_key: ${{ secrets.GITEE_SSH_KEY }}
          dst_token: ${{ secrets.GITEE_API_TOKEN }}
          black_list: '.github'
          static_list: ${{ steps.wppu_repo.outputs. repoList_ALL }}
          src_account_type: org
          dst_account_type: org
          clone_style: ssh
          force_update: true
          debug: true

      - name: Get private-repoes private repository list
        id: pr_repo
        uses: yi-Xu-0100/repo-list-generator@v1.1.1
        with:
          user: private-repoes
          my_token: ${{ secrets.PR_HUB_API_TOKEN }}
      - name: Sync Org(private-repoes) to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/private-repoes
          dst: gitee/private-repoes
          dst_key: ${{ secrets.GITEE_SSH_KEY }}
          dst_token: ${{ secrets.GITEE_API_TOKEN }}
          black_list: '.github'
          static_list: ${{ steps.pr_repo.outputs. repoList_ALL }}
          src_account_type: org
          dst_account_type: org
          clone_style: ssh
          force_update: true
          debug: true

      - name: Sync Org(fork-repoes) to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/fork-repoes
          dst: gitee/fork-repoes
          dst_key: ${{ secrets.GITEE_SSH_KEY }}
          dst_token: ${{ secrets.GITEE_API_TOKEN }}
          src_account_type: org
          dst_account_type: org
          force_update: true
          debug: true

      - name: Get micro-services-roadmap private repository list
        id: msr_repo
        uses: yi-Xu-0100/repo-list-generator@v1.1.1
        with:
          user: micro-services-roadmap
          my_token: ${{ secrets.MSR_HUB_API_TOKEN }}
      - name: Sync Org(micro-services-roadmap) to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/micro-services-roadmap
          dst: gitee/micro-services-roadmap
          dst_key: ${{ secrets.GITEE_SSH_KEY }}
          dst_token: ${{ secrets.GITEE_API_TOKEN }}
          black_list: '.github,.github-private'
          static_list: ${{ steps.msr_repo.outputs. repoList_ALL }}
          src_account_type: org
          dst_account_type: org
          clone_style: ssh
          force_update: true
          debug: true

      - name: Get own-workers private repository list
        id: own_repo
        uses: yi-Xu-0100/repo-list-generator@v1.1.1
        with:
          user: own-workers
          my_token: ${{ secrets.FULL_KEY }}
      - name: Sync Org(own-workers) to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/own-workers
          dst: gitee/own-worker
          dst_key: ${{ secrets.GITEE_SSH_KEY }}
          dst_token: ${{ secrets.GITEE_API_TOKEN }}
          black_list: '.github'
          static_list: ${{ steps.own_repo.outputs. repoList_ALL }}
          src_account_type: org
          dst_account_type: org
          clone_style: ssh
          force_update: true
          debug: true
