name: Sync ZSH to Gitee

on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
  workflow_dispatch:
  push:
  schedule:
    - cron: '5 18 * * *'

jobs:
  main:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    steps:
      # - name: Sync ZSH(dotfiles) to Gitee
      #   uses: Yikun/hub-mirror-action@v1.3
      #   with:
      #     src: github/Alice52
      #     dst: gitee/github-mirror-zsh
      #     dst_key: ${{ secrets.GITEE_SSH_KEY }}
      #     dst_token: ${{ secrets.GITEE_API_TOKEN }}
      #     mappings: 'dotfiles=>dotfiles'
      #     static_list: 'dotfiles'
      #     src_account_type: user
      #     dst_account_type: org
      #     force_update: true
      #     debug: true


      - name: Sync ZSH(dotfiles) to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/Alice52
          dst: gitee/github-mirror-zsh
          dst_key: ${{ secrets.GITEE_SSH_KEY }}
          dst_token: ${{ secrets.GITEE_API_TOKEN }}
          static_list: 'dotfiles'
          clone_style: ssh
          force_update: true

      - name: Sync ZSH(ohmyzsh) to Gitee
        uses: Yikun/hub-mirror-action@v1.3
        with:
          src: github/ohmyzsh
          dst: gitee/github-mirror-zsh
          dst_key: ${{ secrets.GITEE_SSH_KEY }}
          dst_token: ${{ secrets.GITEE_API_TOKEN }}
          static_list: 'ohmyzsh'
          src_account_type: user
          dst_account_type: org
          force_update: true
          debug: true

      - name: Sync ZSH(zsh) to Gitee
        uses: Yikun/hub-mirror-action@v1.3
        with:
          src: github/zsh-users
          dst: gitee/github-mirror-zsh
          dst_key: ${{ secrets.GITEE_SSH_KEY }}
          dst_token: ${{ secrets.GITEE_API_TOKEN }}
          static_list: 'zsh'
          src_account_type: user
          dst_account_type: org
          force_update: true
          debug: true

      - name: Sync ZSH(zsh-z) to Gitee
        uses: Yikun/hub-mirror-action@v1.3
        with:
          src: github/agkozak
          dst: gitee/github-mirror-zsh
          dst_key: ${{ secrets.GITEE_SSH_KEY }}
          dst_token: ${{ secrets.GITEE_API_TOKEN }}
          static_list: 'zsh-z'
          src_account_type: user
          dst_account_type: org
          force_update: true
          debug: true

      - name: Sync ZSH(zsh-syntax-highlighting) to Gitee
        uses: Yikun/hub-mirror-action@v1.3
        with:
          src: github/zsh-users
          dst: gitee/github-mirror-zsh
          dst_key: ${{ secrets.GITEE_SSH_KEY }}
          dst_token: ${{ secrets.GITEE_API_TOKEN }}
          static_list: 'zsh-syntax-highlighting'
          src_account_type: user
          dst_account_type: org
          force_update: true
          debug: true

      - name: Sync ZSH(zsh-autosuggestions) to Gitee
        uses: Yikun/hub-mirror-action@v1.3
        with:
          src: github/zsh-users
          dst: gitee/github-mirror-zsh
          dst_key: ${{ secrets.GITEE_SSH_KEY }}
          dst_token: ${{ secrets.GITEE_API_TOKEN }}
          static_list: 'zsh-autosuggestions'
          src_account_type: user
          dst_account_type: org
          force_update: true
          debug: true

      - name: Sync ZSH(spaceship-prompt) to Gitee
        uses: Yikun/hub-mirror-action@v1.3
        with:
          src: github/spaceship-prompt
          dst: gitee/github-mirror-zsh
          dst_key: ${{ secrets.GITEE_SSH_KEY }}
          dst_token: ${{ secrets.GITEE_API_TOKEN }}
          static_list: 'spaceship-prompt'
          src_account_type: user
          dst_account_type: org
          force_update: true
          debug: true
